// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calculate_distancessq_cpp
NumericMatrix calculate_distancessq_cpp(NumericMatrix x, NumericMatrix v);
RcppExport SEXP _QUEST_calculate_distancessq_cpp(SEXP xSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_distancessq_cpp(x, v));
    return rcpp_result_gen;
END_RCPP
}
// calculate_min_distance_cpp
double calculate_min_distance_cpp(NumericMatrix v);
RcppExport SEXP _QUEST_calculate_min_distance_cpp(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_min_distance_cpp(v));
    return rcpp_result_gen;
END_RCPP
}
// calculate_vdiff_cpp
NumericVector calculate_vdiff_cpp(NumericMatrix v);
RcppExport SEXP _QUEST_calculate_vdiff_cpp(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_vdiff_cpp(v));
    return rcpp_result_gen;
END_RCPP
}
// calculate_finalxb_index_cpp
double calculate_finalxb_index_cpp(NumericMatrix u, NumericMatrix D, double minv, double m, int n);
RcppExport SEXP _QUEST_calculate_finalxb_index_cpp(SEXP uSEXP, SEXP DSEXP, SEXP minvSEXP, SEXP mSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type D(DSEXP);
    Rcpp::traits::input_parameter< double >::type minv(minvSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_finalxb_index_cpp(u, D, minv, m, n));
    return rcpp_result_gen;
END_RCPP
}
// calculate_finalkwon_index_cpp
double calculate_finalkwon_index_cpp(NumericMatrix u, NumericMatrix D, NumericVector vdiff, double minv, double m, int k);
RcppExport SEXP _QUEST_calculate_finalkwon_index_cpp(SEXP uSEXP, SEXP DSEXP, SEXP vdiffSEXP, SEXP minvSEXP, SEXP mSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type D(DSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vdiff(vdiffSEXP);
    Rcpp::traits::input_parameter< double >::type minv(minvSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_finalkwon_index_cpp(u, D, vdiff, minv, m, k));
    return rcpp_result_gen;
END_RCPP
}
// calculate_dissimilarities_cpp
NumericMatrix calculate_dissimilarities_cpp(NumericMatrix x, NumericMatrix centers);
RcppExport SEXP _QUEST_calculate_dissimilarities_cpp(SEXP xSEXP, SEXP centersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type centers(centersSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_dissimilarities_cpp(x, centers));
    return rcpp_result_gen;
END_RCPP
}
// update_memberships_cpp
NumericMatrix update_memberships_cpp(NumericMatrix d, double m);
RcppExport SEXP _QUEST_update_memberships_cpp(SEXP dSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(update_memberships_cpp(d, m));
    return rcpp_result_gen;
END_RCPP
}
// update_prototypes_cpp
NumericMatrix update_prototypes_cpp(NumericMatrix x, NumericMatrix u, double m);
RcppExport SEXP _QUEST_update_prototypes_cpp(SEXP xSEXP, SEXP uSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(update_prototypes_cpp(x, u, m));
    return rcpp_result_gen;
END_RCPP
}
// calculate_error_cpp
double calculate_error_cpp(NumericMatrix u, NumericMatrix d, double m);
RcppExport SEXP _QUEST_calculate_error_cpp(SEXP uSEXP, SEXP dSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_error_cpp(u, d, m));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_QUEST_calculate_distancessq_cpp", (DL_FUNC) &_QUEST_calculate_distancessq_cpp, 2},
    {"_QUEST_calculate_min_distance_cpp", (DL_FUNC) &_QUEST_calculate_min_distance_cpp, 1},
    {"_QUEST_calculate_vdiff_cpp", (DL_FUNC) &_QUEST_calculate_vdiff_cpp, 1},
    {"_QUEST_calculate_finalxb_index_cpp", (DL_FUNC) &_QUEST_calculate_finalxb_index_cpp, 5},
    {"_QUEST_calculate_finalkwon_index_cpp", (DL_FUNC) &_QUEST_calculate_finalkwon_index_cpp, 6},
    {"_QUEST_calculate_dissimilarities_cpp", (DL_FUNC) &_QUEST_calculate_dissimilarities_cpp, 2},
    {"_QUEST_update_memberships_cpp", (DL_FUNC) &_QUEST_update_memberships_cpp, 2},
    {"_QUEST_update_prototypes_cpp", (DL_FUNC) &_QUEST_update_prototypes_cpp, 3},
    {"_QUEST_calculate_error_cpp", (DL_FUNC) &_QUEST_calculate_error_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_QUEST(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
