# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_distancessq_cpp <- function(x, v) {
    .Call(`_QUEST_calculate_distancessq_cpp`, x, v)
}

calculate_min_distance_cpp <- function(v) {
    .Call(`_QUEST_calculate_min_distance_cpp`, v)
}

calculate_vdiff_cpp <- function(v) {
    .Call(`_QUEST_calculate_vdiff_cpp`, v)
}

calculate_finalxb_index_cpp <- function(u, D, minv, m, n) {
    .Call(`_QUEST_calculate_finalxb_index_cpp`, u, D, minv, m, n)
}

calculate_finalkwon_index_cpp <- function(u, D, vdiff, minv, m, k) {
    .Call(`_QUEST_calculate_finalkwon_index_cpp`, u, D, vdiff, minv, m, k)
}

calculate_dissimilarities_cpp <- function(x, centers) {
    .Call(`_QUEST_calculate_dissimilarities_cpp`, x, centers)
}

update_memberships_cpp <- function(d, m) {
    .Call(`_QUEST_update_memberships_cpp`, d, m)
}

update_prototypes_cpp <- function(x, u, m) {
    .Call(`_QUEST_update_prototypes_cpp`, x, u, m)
}

calculate_error_cpp <- function(u, d, m) {
    .Call(`_QUEST_calculate_error_cpp`, u, d, m)
}

